[package]
name = "oxkv"
version = "0.2.0"
edition = "2024"
description = "A transactional key-value store with WASM bindings, cursor pagination."
license = "MIT OR Apache-2.0"
repository = "https://github.com/azamaulanaaa/oxkv"
keywords = ["wasm", "keyvalue", "kv-store", "transaction"]
categories = ["wasm", "database", "data-structures"]
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
futures = { version = "0.3", default-features = false, features = ["std"] }
pest = "2.9.0"
pest_derive = "2.9.0"
redb = "4.2.0"
regex = "1"
serde = "1"
serde_json = "1"
strsim = "0.11"
thiserror = "2"

[[bench]]
name = "kv_bench"
harness = false

[[bench]]
name = "query_bench"
harness = false

[dev-dependencies]
criterion = "0.7"
mockall = "0.15"
tokio = { version = "1.53.1", features = ["test-util", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"
unreachable_pub = "deny"

[lints.clippy]
all = "deny"
cargo = "deny"
pedantic = "deny"
