[tools]
rust = { version = "stable", components = "rust-analyzer" }
zig = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:wasm-pack" = "latest"
node = "latest"

[tasks]
cov = { run = "cargo-zigbuild llvm-cov --all-targets" }
test = { run = "cargo-zigbuild test --all-targets" }
wasm = { run = "rm -rf pkg && wasm-pack build --target web --release --out-dir pkg" }
publish-npm = { run = "npm publish ./pkg", depends = ["wasm"] }
