[tools]
rust = { version = "stable", components = "rust-analyzer" }
zig = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:wasm-pack" = "latest"
node = "latest"
"cargo:cargo-llvm-cov" = "latest"

[env]
RUSTUP_TOOLCHAIN = "{% if os() == 'windows' %}stable-x86_64-pc-windows-msvc{% endif %}"
CARGO_BUILD_TARGET = "{% if os() == 'windows' %}x86_64-pc-windows-msvc{% endif %}"

[tasks]
cov = { run = "cargo-zigbuild llvm-cov --all-targets" }
test = { run = "cargo-zigbuild test --all-targets" }
wasm = { run = "rm -rf pkg && wasm-pack build --target web --release --out-dir pkg" }
publish-npm = { run = "npm publish ./pkg", depends = ["wasm"] }
