[tools]
rust = { version = "stable", components = "rust-analyzer" }
zig = "latest"
"cargo:cargo-zigbuild" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:wasm-pack" = "latest"
node = "latest"

[tasks]
cov = { run = "cargo-zigbuild llvm-cov" }
test = { run = "cargo-zigbuild test" }
bench = { run = "cargo-zigbuild bench" }
